[package]
name = "arc4zen"
version = "0.1.0"
edition = "2024"

[dependencies]
rusqlite = "0.37.0"
serde = "1.0.219"
serde_json = "1.0.143"

[dependencies.uuid]
version = "1.18.1"
features = [
    "v4",
]
